name = "nanx2021"
license = "MIT"
licenselink = "https://github.com/nanxstats/hugo-nanx2021/blob/master/LICENSE"
description = "A minimalist Hugo theme built on Bootstrap 5."
homepage = "https://github.com/nanxstats/hugo-nanx2021"
tags = ["bootstrap", "minimalist", "responsive", "typography"]
min_version = 0.17

[author]
  name = "Nan Xiao"
  homepage = "https://nanx.me"
  repo = "https://github.com/nanxstats/hugo-nanx2021"

[original]
    name = "Nan Xiao"
    homepage = "https://nanx.me"
    repo = "https://github.com/nanxstats/hugo-nanx2020"
